//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DangKy
    {
        [Display(Name = "Mã Đăng Ký")]
        public string MaDangKy { get; set; }
        [Display(Name = "Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Mã Loại Vé Số")]
        public string MaLoaiVeSo { get; set; }
        [Display(Name = "Ngày Đăng Ký")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        [Display(Name = "Ngày Phân Phối")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayPhanPhoi { get; set; }
        [Display(Name = "Số Lượng")]
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual LoaiVeSo LoaiVeSo { get; set; }
    }
}
