//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaSoXo
    {
        public int ID { get; set; }
        public string MaLoaiVeSo { get; set; }
        public string MaGiai { get; set; }
        public Nullable<System.DateTime> NgaySo { get; set; }
        public string SoTrung { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual Giai Giai { get; set; }
        public virtual LoaiVeso LoaiVeso { get; set; }
    }
}
