//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KetQuaXoSo
    {
        [Display(Name = "Mã Kết Quả")]
        public string MaKetQua { get; set; }
        [Display(Name = "Mã Loại Vé Số")]
        public string MaLoaiVeSo { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        [Display(Name = "Ngày Xổ")]
        public Nullable<System.DateTime> Ngay { get; set; }
        [Display(Name = "Số Trúng")]
        public string SoTrung { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual LoaiVeSo LoaiVeSo { get; set; }
    }
}
