//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhanPhoi
    {
        [Display(Name = "Mã Phân Phối")]
        public string MaPhanPhoi { get; set; }
        [Display(Name = "Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Mã Loại Vé Số")]
        public string MaLoaiVeSo { get; set; }
        [Display(Name = "Ngày Phân Phối")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayPhanPhoi { get; set; }
        [Display(Name = "Số Lượng Giao")]
        public Nullable<int> SoLuongGiao { get; set; }
        [Display(Name = "Số Lượng Bán")]
        public Nullable<int> SoLuongBan { get; set; }
        [Display(Name = "Tỉ Lệ")]
        public Nullable<double> TiLe { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public void khoitao(string MaPhanPhoi, string MaDaiLy, DaiLy daiLy, LoaiVeSo loaiVeSo, string MaLoaiVeSo, DateTime? dateTime, bool? TinhTrang)
        {
            this.MaPhanPhoi = MaPhanPhoi;
            this.MaDaiLy = MaDaiLy;
            this.DaiLy = daiLy;
            this.LoaiVeSo = LoaiVeSo;
            this.MaLoaiVeSo = MaLoaiVeSo;
            this.NgayPhanPhoi = dateTime;
            this.TinhTrang = TinhTrang;

        }

        public virtual DaiLy DaiLy { get; set; }
        public virtual LoaiVeSo LoaiVeSo { get; set; }
    }
}
