//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PhatHanh
    {
        public int ID { get; set; }
        [Display(Name ="Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Mã Loại Vé Số")]
        public string MaLoaiVeSo { get; set; }
        [Display(Name = "Số Lượng")]
        public Nullable<int> SoLuong { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name ="Ngày Nhận")]
        public Nullable<System.DateTime> NgayNhan { get; set; }
        [Display(Name = "Số Lượng Bán Được")]
        public Nullable<int> SLBan { get; set; }
        [Display(Name = "Doanh Thu")]
        public Nullable<decimal> DoanhThuDPH { get; set; }
        [Display(Name = "Hoa Hồng")]
        [DisplayFormat(DataFormatString ="{0:F2}%" )]
        public Nullable<decimal> HoaHong { get; set; }
        [Display(Name = "Tiền Thanh Toán")]
        public Nullable<decimal> TienThanhToan { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual LoaiVeso LoaiVeso { get; set; }
    }
}
