//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuThu
    {

        [Display(Name = "Mã Phiếu Thu")]
        public string MaPhieuThu { get; set; }
        [Display(Name = "Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Ngày Nộp")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Ngay { get; set; }
        [Display(Name = "Tiền Thanh Toán")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> TienThanhToan { get; set; }
        [DataType(DataType.Currency)]
        [Display(Name = "Tiền Đã Thu")]
        public Nullable<decimal> SoTienThuDuoc { get; set; }
        [DataType(DataType.Currency)]
        [Display(Name = "Công Nợ")]
        public Nullable<decimal> CongNo { get; set; }
        [Display(Name = "Hoa Hồng")]
        public Nullable<int> HoaHong { get; set; }
        [Display(Name = "Giá Vé")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
    }
}
