//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuChi
    {
        [Display(Name ="Mã Phiếu Chi")]
        public string MaPhieuChi { get; set; }
        [Display(Name ="Ngày")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Ngay { get; set; }
        [DataType(DataType.Currency)]
        [Display(Name ="Thành Tiền")]
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    }
}
