//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public string MaPhieuThu { get; set; }
        public string MaDaiLy { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<decimal> SoTienNop { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
    }
}
