//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
   
    public partial class SoLuongDK
    {
        public string ID { get; set; }
        [Display(Name ="Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Ngày Đăng Ký")]
        
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayDK { get; set; }
        [Display(Name = "Số Lượng Đăng Ký")]
        public Nullable<int> SoLuongDK1 { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
    }
}
